DATA ANALYSIS ASSIGNMENT 

In [2]:
import numpy as np

In [9]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
matrix = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(numbers)
print (matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [31]:
#Get dimension
matrix.ndim

2

In [32]:
#shape
matrix.shape

(3, 3)

In [34]:
#type
matrix.dtype

dtype('int64')

In [8]:
matrix = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(matrix)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
#2D array (3×4)
matrix = np.array([[2,3,4,5], [6,7,8,9],[10,11,12,13]])
print (matrix)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [17]:
arr2d = np.ones((3, 4))
print("\n2D Array (3×4) of ones:")
print(arr2d)


2D Array (3×4) of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
#3×3 identity matrix
matrix = np.array([[1,0,0], [0,1,0],[0,0,1]])
print (matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
#3×3 identity matrix
identity = np.eye(3)
print("\n3×3 Identity Marix:")
print(identity)


3×3 Identity Marix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#Get dimension
identity.ndim

2

In [33]:
#shape
identity.shape

(3, 3)

In [35]:
#type
identity.dtype

dtype('float64')

In [38]:
#Create a normal list
Gee = [5, 10, 15, 20, 25, 30]
print(Gee)

[5, 10, 15, 20, 25, 30]


In [39]:
#Convert list to NumPy array
numpy_array = np.array(Gee)
print("\nNumPy Array:")
print(numpy_array)
print("Type:", type(numpy_array))


NumPy Array:
[ 5 10 15 20 25 30]
Type: <class 'numpy.ndarray'>
